//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentMarkSys.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_Table
    {
        public int Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email { get; set; }
        public string PassWord { get; set; }
        public bool Is_Agree { get; set; }
        public bool Is_Deleted { get; set; }
        public System.DateTime Current_Time_Stamp { get; set; }
        public System.DateTime Updated_Time_Stamp { get; set; }
    }
}
