//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentMarkSys.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Dep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student_Dep()
        {
            this.Student_Detail = new HashSet<Student_Detail>();
        }
    
        public int Dep_Id { get; set; }
        public string Dep_Name { get; set; }
        public Nullable<System.DateTime> Created_Time_Stamp { get; set; }
        public Nullable<System.DateTime> Updated_Time_Stamp { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Detail> Student_Detail { get; set; }
    }
}
