//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentMarkSys.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Mark
    {
        public int Mark_Id { get; set; }
        public int Std_Id { get; set; }
        public Nullable<decimal> Mark1 { get; set; }
        public Nullable<decimal> Mark2 { get; set; }
        public Nullable<bool> Is_Delete { get; set; }
    
        public virtual Student_Detail Student_Detail { get; set; }
    }
}
